### ISSUE TITLE
关于代码和数据集性能的gap问题

### ISSUE THREAD

**Issue by cutejue** [LindgeW/BiaffineNER#1]
您好，看了您复现的Ner as DP的pytorch版本代码，受益匪浅，但有几个问题想问下：
1、我在conll_2003和ontonote5上都跑了，但是按照代码的参数，性能和juntaoy的论文结论gap太大，例如conll_2003只到85-86，ontonote5只到82左右，不知道为什么。按照原作者论文所述，bert和word embedding带来的提升也就2.4和0.4，因此gap也不至于那么大
2、为什么在获得bert embedding后还要加个fc抽取为300d的特征，不是很明白
非常感谢

**Comment by LindgeW** [comment]
1、之前有点小问题没更新，utils/vocab.py 和 modules/BertModel_fixed.py 这两个文件做了更新；参数需要你再调
2、这是个人经验，768太大了，需要降下维 （特别是biaffine计算的时候维度太大容易炸）

**Comment by cutejue** [comment]
> 1、之前有点小问题没更新，utils/vocab.py 和 modules/BertModel_fixed.py 这两个文件做了更新；参数需要你再调
> 2、这是个人经验，768太大了，需要降下维 （特别是biaffine计算的时候维度太大容易炸）

我看了更新后的文件，vocab里只去掉了SEP的token，而fixed里变成seq_len（原来是len-2），会出现维度不一致错误诶，是不是要把vocab的CLS也去掉？

**Comment by LindgeW** [comment]
不会错啊，跑起来看看

**Comment by SomeoneNotLikeYou** [comment]
运行 mian_biaf.py后 出现了错误 
![Uploading image.png…]()

**Comment by SomeoneNotLikeYou** [comment]
运行mian_biaf后出现了错误
![image](https://user-images.githubusercontent.com/50167423/114307346-c95d0d00-9b11-11eb-85a2-b73302bc1514.png)

**Comment by LindgeW** [comment]
需要在序列前加一个表示来对齐CLS

**Comment by SomeoneNotLikeYou** [comment]
你跑出来了吗

**Comment by LindgeW** [comment]
en

**Comment by SomeoneNotLikeYou** [comment]
我跑了main_biaf.py 报了ValueError: Expected input batch_size (35344) to match target batch_size (36864).的错误
跑了main_seq.py 报了RuntimeError: Sizes of tensors must match except in dimension 2. Got 48 and 47 in dimension 1 (The offending index is 1)的错误
跑了main_span.py报了KeyError: 'pretrained'
挺不好意思的 我刚学习 调不太出来

**Comment by cutejue** [comment]
hello，我看您后来根据BERTEmbedding的CLS，在word和tag embedding中加入了1位长度，然后从1:seq_len开始赋予wd和tag的idx，然后定义了比原先多一位的mask的输入，以将wd、tag和bert的embedding序列对齐； 
这里我觉得可不可以直接在fixed.py的BERTEmedding中，将最后获得的bert_embed截取cls后序列，即bert_embed=bert_embed.masked_scatter_(mask.unsqueeze(dim=-1), bert_out)[ ,1: , ]？这样就不用修改其他的代码了，我不知道理解的对不对，又或者wd对齐bert有其他好处

**Comment by LindgeW** [comment]
可以试下，截取的效果可能没有对齐的好

**Comment by LindgeW** [comment]
> hello，我看您后来根据BERTEmbedding的CLS，在word和tag embedding中加入了1位长度，然后从1:seq_len开始赋予wd和tag的idx，然后定义了比原先多一位的mask的输入，以将wd、tag和bert的embedding序列对齐；
> 这里我觉得可不可以直接在fixed.py的BERTEmedding中，将最后获得的bert_embed截取cls后序列，即bert_embed=bert_embed.masked_scatter_(mask.unsqueeze(dim=-1), bert_out)[ ,1: , ]？这样就不用修改其他的代码了，我不知道理解的对不对，又或者wd对齐bert有其他好处

可以试下，截取的效果可能没有对齐的好 (CLS和其他token之间是有交互的)
