### ISSUE TITLE
1

### ISSUE THREAD

**Issue by FreeRotate** [LindgeW/BiaffineNER#2]
1

**Comment by AhGiao** [comment]
对于使用main_biaf.py，几个embedding的维度又是一致的，可以拼接并运行代码。main_seq.py在去掉cls标志位也可以拼接运行

**Comment by AhGiao** [comment]
找到问题了，在datautil_seq.py文件中的batch_variable函数需要修改成类似datautils文件的同名函数batch_variable。mask也要跟着修改
