### ISSUE TITLE
你好，关于字典的一个问题

### ISSUE THREAD

**Issue by FreeRotate** [LindgeW/BiaffineNER#3]
请问为什么word_embedding、char_embedding、tag_embedding不直接用bert的vocab.txt字典，而去新建一个编码字典？

**Comment by LindgeW** [comment]
这3类表示是独立于bert embedding的，为什么要用强行和bert的vocabulary建立联系呢？

**Comment by AhGiao** [comment]
我想用一套编码的原因是在想怎么简化代码。如果用不同的编码，bert编码会将单词分为一个个词根，但是vocab类中的单词没有拆分词根编码的操作，后面再拼接这几个embedding，这样不会出现拼接后的总embedding的某一行代表不同的单词吗？又或者出现这种情况无关紧要？我可能描述的有点不清楚，抱歉。
